services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=nyxalon
      - N8N_BASIC_AUTH_PASSWORD=404NotFound!
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
    ports:
      - "53002:5678"
    volumes:
      - core:/home/node/.n8n
    networks:
      - os
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: n8n_postgres
    restart: always
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
    ports:
      - "53003:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - os

volumes:
    core:
    data:

networks:
    os:
      name: os
      external: true
